require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const College = require('../models/College');
const Student = require('../models/Student');

const colleges = [
  // ═══════════════════════════════════════════════════════════════
  // TOP-TIER NATIONAL COLLEGES
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    type: 'IIT',
    tier: 'Tier 1',
    location: { city: 'Mumbai', state: 'Maharashtra', pincode: '400076' },
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 80, fees: 230000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 60, fees: 230000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 60, fees: 230000 },
    ],
    rankings: { nirf: 3, qs: 149 },
    averageFees: 230000,
    entranceExams: ['JEE Advanced'],
    accreditation: 'NAAC A++',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1958,
    website: 'https://www.iitb.ac.in',
    placementData: [{
      year: 2024, averagePackage: 28, highestPackage: 130,
      placementRate: 94, topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Goldman Sachs'],
    }],
    facilities: ['Library', 'Research Labs', 'Hostels', 'Sports Complex', 'Hospital'],
    aiRatingScore: 98,
    overallRating: 4.8,
    isVerified: true,
  },
  {
    name: 'Indian Institute of Technology Delhi',
    shortName: 'IIT Delhi',
    type: 'IIT',
    tier: 'Tier 1',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110016' },
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 75, fees: 220000 },
      { name: 'B.Tech Electronics', duration: 4, seats: 60, fees: 220000 },
      { name: 'M.Tech AI & ML', duration: 2, seats: 30, fees: 240000 },
    ],
    rankings: { nirf: 2, qs: 197 },
    averageFees: 220000,
    entranceExams: ['JEE Advanced'],
    accreditation: 'NAAC A++',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1961,
    website: 'https://home.iitd.ac.in',
    placementData: [{
      year: 2024, averagePackage: 27.5, highestPackage: 120,
      placementRate: 95, topRecruiters: ['Google', 'Apple', 'Uber', 'Tower Research'],
    }],
    facilities: ['Research Centers', 'Innovation Hub', 'Sports', 'Hostels'],
    aiRatingScore: 97,
    overallRating: 4.8,
    isVerified: true,
  },
  {
    name: 'BITS Pilani',
    shortName: 'BITS Pilani',
    type: 'Deemed',
    tier: 'Tier 1',
    location: { city: 'Pilani', state: 'Rajasthan', pincode: '333031' },
    courses: [
      { name: 'B.E. Computer Science', duration: 4, seats: 180, fees: 580000 },
      { name: 'B.E. Electronics', duration: 4, seats: 120, fees: 560000 },
      { name: 'B.Pharm', duration: 4, seats: 80, fees: 480000 },
    ],
    rankings: { nirf: 22, qs: 591 },
    averageFees: 580000,
    entranceExams: ['BITSAT'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC'],
    establishedYear: 1964,
    website: 'https://www.bits-pilani.ac.in',
    placementData: [{
      year: 2024, averagePackage: 22, highestPackage: 85,
      placementRate: 90, topRecruiters: ['Qualcomm', 'Samsung', 'Microsoft', 'Flipkart'],
    }],
    facilities: ['Libraries', 'Labs', 'Auditorium', 'Sports', 'Health Center'],
    aiRatingScore: 92,
    overallRating: 4.5,
    isVerified: true,
  },
  {
    name: 'National Institute of Technology Trichy',
    shortName: 'NIT Trichy',
    type: 'NIT',
    tier: 'Tier 1',
    location: { city: 'Tiruchirappalli', state: 'Tamil Nadu', pincode: '620015' },
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 60, fees: 170000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 60, fees: 150000 },
      { name: 'B.Tech Mechanical', duration: 4, seats: 60, fees: 150000 },
    ],
    rankings: { nirf: 8 },
    averageFees: 160000,
    entranceExams: ['JEE Mains'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1964,
    website: 'https://www.nitt.edu',
    placementData: [{
      year: 2024, averagePackage: 15, highestPackage: 60,
      placementRate: 85, topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Zoho'],
    }],
    facilities: ['Central Library', 'Labs', 'Hostels', 'Sports'],
    aiRatingScore: 88,
    overallRating: 4.4,
    isVerified: true,
  },
  {
    name: 'VIT Vellore',
    shortName: 'VIT',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Vellore', state: 'Tamil Nadu', pincode: '632014' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 500, fees: 380000 },
      { name: 'B.Tech Mechatronics', duration: 4, seats: 120, fees: 350000 },
      { name: 'MBA', duration: 2, seats: 240, fees: 450000 },
    ],
    rankings: { nirf: 11 },
    averageFees: 380000,
    entranceExams: ['VITEEE'],
    accreditation: 'NAAC A++',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1984,
    website: 'https://vit.ac.in',
    placementData: [{
      year: 2024, averagePackage: 8, highestPackage: 45,
      placementRate: 82, topRecruiters: ['TCS', 'CTS', 'Infosys', 'Amazon', 'Zoho'],
    }],
    facilities: ['Smart Classrooms', 'Labs', 'Hostels', 'Food Courts', 'Sports'],
    aiRatingScore: 83,
    overallRating: 4.1,
    isVerified: true,
  },
  {
    name: 'Delhi Technological University',
    shortName: 'DTU',
    type: 'State University',
    tier: 'Tier 2',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110042' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 90, fees: 120000 },
      { name: 'B.Tech IT', duration: 4, seats: 90, fees: 120000 },
      { name: 'B.Tech ECE', duration: 4, seats: 90, fees: 110000 },
    ],
    rankings: { nirf: 36 },
    averageFees: 120000,
    entranceExams: ['JEE Mains'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1941,
    website: 'http://dtu.ac.in',
    placementData: [{
      year: 2024, averagePackage: 12, highestPackage: 60,
      placementRate: 80, topRecruiters: ['Amazon', 'Microsoft', 'Samsung', 'Deloitte'],
    }],
    facilities: ['Library', 'Labs', 'Hostels', 'Sports Complex'],
    aiRatingScore: 80,
    overallRating: 4.0,
    isVerified: true,
  },
  {
    name: 'Amity University Noida',
    shortName: 'Amity',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Noida', state: 'Uttar Pradesh', pincode: '201313' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 300, fees: 400000 },
      { name: 'BBA', duration: 3, seats: 200, fees: 280000 },
      { name: 'B.Sc Psychology', duration: 3, seats: 120, fees: 220000 },
    ],
    rankings: { nirf: 45 },
    averageFees: 400000,
    entranceExams: ['AUSAT'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC'],
    establishedYear: 2005,
    website: 'https://www.amity.edu',
    placementData: [{
      year: 2024, averagePackage: 6, highestPackage: 25,
      placementRate: 75, topRecruiters: ['TCS', 'Wipro', 'HCL', 'Deloitte'],
    }],
    facilities: ['Smart Campus', 'Labs', 'Hostels', 'Sports', 'Food Courts'],
    aiRatingScore: 72,
    overallRating: 3.8,
    isVerified: true,
  },
  {
    name: 'Manipal Institute of Technology',
    shortName: 'MIT Manipal',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Manipal', state: 'Karnataka', pincode: '576104' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 300, fees: 480000 },
      { name: 'B.Tech Biomedical', duration: 4, seats: 60, fees: 400000 },
      { name: 'M.Tech', duration: 2, seats: 60, fees: 350000 },
    ],
    rankings: { nirf: 35 },
    averageFees: 480000,
    entranceExams: ['MET'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1957,
    website: 'https://manipal.edu/mit',
    placementData: [{
      year: 2024, averagePackage: 9, highestPackage: 40,
      placementRate: 83, topRecruiters: ['Infosys', 'Wipro', 'TCS', 'Capgemini'],
    }],
    facilities: ['Innovation Center', 'Labs', 'Hostels', 'Hospital'],
    aiRatingScore: 82,
    overallRating: 4.1,
    isVerified: true,
  },
  {
    name: 'SRM Institute of Science and Technology',
    shortName: 'SRM',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Chennai', state: 'Tamil Nadu', pincode: '603203' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 600, fees: 350000 },
      { name: 'B.Tech AI & ML', duration: 4, seats: 150, fees: 380000 },
      { name: 'MBBS', duration: 5.5, seats: 150, fees: 1500000 },
    ],
    rankings: { nirf: 28 },
    averageFees: 350000,
    entranceExams: ['SRMJEEE'],
    accreditation: 'NAAC A++',
    approvedBy: ['UGC', 'AICTE', 'MCI'],
    establishedYear: 1985,
    website: 'https://www.srmist.edu.in',
    placementData: [{
      year: 2024, averagePackage: 7, highestPackage: 35,
      placementRate: 78, topRecruiters: ['TCS', 'CTS', 'Accenture', 'IBM'],
    }],
    facilities: ['Advanced Labs', 'Hospital', 'Sports', 'Hostels'],
    aiRatingScore: 78,
    overallRating: 4.0,
    isVerified: true,
  },
  {
    name: 'Thapar Institute of Engineering & Technology',
    shortName: 'Thapar University',
    type: 'Deemed',
    tier: 'Tier 2',
    location: { city: 'Patiala', state: 'Punjab', pincode: '147004' },
    courses: [
      { name: 'B.E. CSE', duration: 4, seats: 180, fees: 430000 },
      { name: 'B.E. Electrical', duration: 4, seats: 120, fees: 410000 },
    ],
    rankings: { nirf: 30 },
    averageFees: 430000,
    entranceExams: ['JEE Mains'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1956,
    website: 'https://www.thapar.edu',
    placementData: [{
      year: 2024, averagePackage: 10, highestPackage: 42,
      placementRate: 84, topRecruiters: ['Amazon', 'Microsoft', 'Adobe', 'Samsung'],
    }],
    facilities: ['Library', 'Innovation Labs', 'Hostels', 'Sports'],
    aiRatingScore: 80,
    overallRating: 4.2,
    isVerified: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // NCR DELHI REGION COLLEGES & UNIVERSITIES
  // ═══════════════════════════════════════════════════════════════

  // ─── New Delhi (Central) ─────────────────────────────────────
  {
    name: 'Jawaharlal Nehru University',
    shortName: 'JNU',
    type: 'Central University',
    tier: 'Tier 1',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110067' },
    courses: [
      { name: 'M.A. Political Science', duration: 2, seats: 60, fees: 4000 },
      { name: 'M.Sc. Biotechnology', duration: 2, seats: 40, fees: 8000 },
      { name: 'Ph.D. Social Sciences', duration: 5, seats: 100, fees: 6000 },
    ],
    rankings: { nirf: 2, qs: 521 },
    averageFees: 6000,
    entranceExams: ['JNUEE', 'CUET'],
    accreditation: 'NAAC A++',
    approvedBy: ['UGC'],
    establishedYear: 1969,
    website: 'https://www.jnu.ac.in',
    placementData: [{
      year: 2024, averagePackage: 7, highestPackage: 18,
      placementRate: 72, topRecruiters: ['UPSC', 'Research Orgs', 'NGOs', 'Media'],
    }],
    facilities: ['Ganga Dhaba', 'Central Library', 'Hostels', 'Sabarmati Hostel', 'Sports Complex', 'Health Centre'],
    aiRatingScore: 94,
    overallRating: 4.6,
    isVerified: true,
  },
  {
    name: 'University of Delhi',
    shortName: 'DU',
    type: 'Central University',
    tier: 'Tier 1',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110007' },
    courses: [
      { name: 'B.Com (Hons)', duration: 3, seats: 500, fees: 15000 },
      { name: 'B.A. Economics (Hons)', duration: 3, seats: 300, fees: 12000 },
      { name: 'B.Sc. (H) Computer Science', duration: 3, seats: 240, fees: 18000 },
      { name: 'MBA', duration: 2, seats: 120, fees: 35000 },
    ],
    rankings: { nirf: 12, qs: 407 },
    averageFees: 20000,
    entranceExams: ['CUET'],
    accreditation: 'NAAC A++',
    approvedBy: ['UGC'],
    establishedYear: 1922,
    website: 'https://www.du.ac.in',
    placementData: [{
      year: 2024, averagePackage: 8, highestPackage: 40,
      placementRate: 78, topRecruiters: ['Deloitte', 'EY', 'KPMG', 'BCG', 'McKinsey'],
    }],
    facilities: ['Multiple Libraries', '77+ Colleges', 'Sports Complex', 'NSS/NCC', 'Cultural Fests'],
    aiRatingScore: 88,
    overallRating: 4.4,
    isVerified: true,
  },
  {
    name: 'Jamia Millia Islamia',
    shortName: 'Jamia',
    type: 'Central University',
    tier: 'Tier 1',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110025' },
    courses: [
      { name: 'B.Tech Computer Engineering', duration: 4, seats: 60, fees: 65000 },
      { name: 'B.A. Mass Communication', duration: 3, seats: 40, fees: 35000 },
      { name: 'MBA', duration: 2, seats: 60, fees: 80000 },
      { name: 'B.Ed', duration: 2, seats: 100, fees: 20000 },
    ],
    rankings: { nirf: 8 },
    averageFees: 60000,
    entranceExams: ['JMI Entrance', 'CUET'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1920,
    website: 'https://www.jmi.ac.in',
    placementData: [{
      year: 2024, averagePackage: 7, highestPackage: 22,
      placementRate: 70, topRecruiters: ['TCS', 'Infosys', 'Doordarshan', 'ABP News'],
    }],
    facilities: ['Dr. Zakir Husain Library', 'Hostels', 'Sports', 'AJK-MCRC Studio', 'Hospital'],
    aiRatingScore: 82,
    overallRating: 4.1,
    isVerified: true,
  },
  {
    name: 'Netaji Subhas University of Technology',
    shortName: 'NSUT',
    type: 'State University',
    tier: 'Tier 2',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110078' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 90, fees: 130000 },
      { name: 'B.Tech IT', duration: 4, seats: 90, fees: 130000 },
      { name: 'B.Tech Electronics', duration: 4, seats: 90, fees: 120000 },
      { name: 'M.Tech', duration: 2, seats: 60, fees: 90000 },
    ],
    rankings: { nirf: 51 },
    averageFees: 130000,
    entranceExams: ['JEE Mains'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1983,
    website: 'https://nsut.ac.in',
    placementData: [{
      year: 2024, averagePackage: 11, highestPackage: 52,
      placementRate: 82, topRecruiters: ['Amazon', 'Microsoft', 'Wipro', 'HCL', 'Samsung'],
    }],
    facilities: ['Central Library', 'Labs', 'Sports', 'Hostels', 'Canteen'],
    aiRatingScore: 79,
    overallRating: 4.0,
    isVerified: true,
  },
  {
    name: 'Indraprastha Institute of Information Technology Delhi',
    shortName: 'IIIT Delhi',
    type: 'State University',
    tier: 'Tier 2',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110020' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 120, fees: 330000 },
      { name: 'B.Tech ECE', duration: 4, seats: 60, fees: 330000 },
      { name: 'M.Tech CS', duration: 2, seats: 40, fees: 200000 },
      { name: 'Ph.D.', duration: 4, seats: 30, fees: 50000 },
    ],
    rankings: { nirf: 44 },
    averageFees: 330000,
    entranceExams: ['JEE Mains', 'IIITD Entrance'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 2008,
    website: 'https://www.iiitd.ac.in',
    placementData: [{
      year: 2024, averagePackage: 18, highestPackage: 75,
      placementRate: 88, topRecruiters: ['Google', 'Adobe', 'Samsung R&D', 'Goldman Sachs', 'D.E. Shaw'],
    }],
    facilities: ['Research Labs', 'Library', 'Hostels', 'Innovation Hub', 'Sports'],
    aiRatingScore: 86,
    overallRating: 4.3,
    isVerified: true,
  },
  {
    name: 'Indira Gandhi Delhi Technical University for Women',
    shortName: 'IGDTUW',
    type: 'State University',
    tier: 'Tier 2',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110006' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 60, fees: 110000 },
      { name: 'B.Tech IT', duration: 4, seats: 60, fees: 110000 },
      { name: 'B.Tech ECE', duration: 4, seats: 60, fees: 110000 },
    ],
    rankings: { nirf: 88 },
    averageFees: 110000,
    entranceExams: ['JEE Mains'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 1998,
    website: 'https://www.igdtuw.ac.in',
    placementData: [{
      year: 2024, averagePackage: 9, highestPackage: 38,
      placementRate: 78, topRecruiters: ['TCS', 'Accenture', 'Infosys', 'Amazon'],
    }],
    facilities: ['Library', 'Labs', 'Hostels', 'Sports', 'Incubation Centre'],
    aiRatingScore: 75,
    overallRating: 3.9,
    isVerified: true,
  },
  {
    name: 'Guru Gobind Singh Indraprastha University',
    shortName: 'GGSIPU / IPU',
    type: 'State University',
    tier: 'Tier 2',
    location: { city: 'New Delhi', state: 'Delhi', pincode: '110078' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 300, fees: 140000 },
      { name: 'BBA', duration: 3, seats: 200, fees: 90000 },
      { name: 'MBA', duration: 2, seats: 180, fees: 120000 },
      { name: 'LLB', duration: 3, seats: 120, fees: 75000 },
    ],
    rankings: { nirf: 55 },
    averageFees: 140000,
    entranceExams: ['IPU CET'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC', 'AICTE', 'BCI'],
    establishedYear: 1998,
    website: 'https://ipu.ac.in',
    placementData: [{
      year: 2024, averagePackage: 7, highestPackage: 30,
      placementRate: 72, topRecruiters: ['Infosys', 'Wipro', 'HCL', 'Cognizant'],
    }],
    facilities: ['Multiple Campuses', 'Library', 'Labs', 'Sports', 'Hostels'],
    aiRatingScore: 72,
    overallRating: 3.8,
    isVerified: true,
  },

  // ─── Noida & Greater Noida ────────────────────────────────────
  {
    name: 'Sharda University',
    shortName: 'Sharda',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Greater Noida', state: 'Uttar Pradesh', pincode: '201310' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 400, fees: 200000 },
      { name: 'MBBS', duration: 5, seats: 150, fees: 1200000 },
      { name: 'MBA', duration: 2, seats: 240, fees: 220000 },
      { name: 'B.Pharm', duration: 4, seats: 100, fees: 130000 },
    ],
    rankings: { nirf: 60 },
    averageFees: 200000,
    entranceExams: ['JEE Mains', 'NEET', 'SUJEEET'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC', 'AICTE', 'MCI'],
    establishedYear: 2009,
    website: 'https://www.sharda.ac.in',
    placementData: [{
      year: 2024, averagePackage: 5, highestPackage: 22,
      placementRate: 70, topRecruiters: ['TCS', 'Wipro', 'HCL', 'Infosys', 'Capgemini'],
    }],
    facilities: ['International Campus', 'Hospital', 'Labs', 'Hostels', 'Sports', 'Food Courts'],
    aiRatingScore: 70,
    overallRating: 3.7,
    isVerified: true,
  },
  {
    name: 'Galgotias University',
    shortName: 'Galgotias',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Greater Noida', state: 'Uttar Pradesh', pincode: '201310' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 600, fees: 180000 },
      { name: 'B.Tech AI & ML', duration: 4, seats: 180, fees: 200000 },
      { name: 'BCA', duration: 3, seats: 240, fees: 120000 },
      { name: 'MBA', duration: 2, seats: 180, fees: 200000 },
    ],
    rankings: { nirf: 76 },
    averageFees: 185000,
    entranceExams: ['JEE Mains', 'GSAT', 'SAT'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 2011,
    website: 'https://galgotiasuniversity.edu.in',
    placementData: [{
      year: 2024, averagePackage: 5.5, highestPackage: 25,
      placementRate: 73, topRecruiters: ['TCS', 'Cognizant', 'Accenture', 'Infosys', 'Amazon'],
    }],
    facilities: ['Smart Labs', 'Hostels', 'Sports', 'Food Court', 'Innovation Hub'],
    aiRatingScore: 68,
    overallRating: 3.6,
    isVerified: true,
  },
  {
    name: 'Bennett University',
    shortName: 'Bennett (Times Group)',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Greater Noida', state: 'Uttar Pradesh', pincode: '201310' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 300, fees: 450000 },
      { name: 'B.Tech CSE (AI)', duration: 4, seats: 120, fees: 475000 },
      { name: 'BBA', duration: 3, seats: 180, fees: 280000 },
      { name: 'B.Journalism & Mass Comm', duration: 3, seats: 120, fees: 320000 },
    ],
    rankings: { nirf: 95 },
    averageFees: 450000,
    entranceExams: ['JEE Mains', 'Bennett Entrance'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 2016,
    website: 'https://www.bennett.edu.in',
    placementData: [{
      year: 2024, averagePackage: 8, highestPackage: 35,
      placementRate: 76, topRecruiters: ['TCS', 'Google', 'Times Group', 'PwC', 'Deloitte'],
    }],
    facilities: ['Times Group Mentorship', 'Media Labs', 'Hostels', 'Sports', 'Innovation Centre'],
    aiRatingScore: 73,
    overallRating: 3.9,
    isVerified: true,
  },
  {
    name: 'Jaypee Institute of Information Technology',
    shortName: 'JIIT Noida',
    type: 'Deemed',
    tier: 'Tier 2',
    location: { city: 'Noida', state: 'Uttar Pradesh', pincode: '201307' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 240, fees: 300000 },
      { name: 'B.Tech ECE', duration: 4, seats: 180, fees: 285000 },
      { name: 'B.Tech IT', duration: 4, seats: 120, fees: 280000 },
      { name: 'M.Tech', duration: 2, seats: 60, fees: 200000 },
    ],
    rankings: { nirf: 68 },
    averageFees: 295000,
    entranceExams: ['JEE Mains', 'JIIT Entrance'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 2001,
    website: 'https://www.jiit.ac.in',
    placementData: [{
      year: 2024, averagePackage: 10, highestPackage: 42,
      placementRate: 80, topRecruiters: ['Amazon', 'Adobe', 'Samsung', 'Publicis Sapient', 'Wipro'],
    }],
    facilities: ['Library', 'Research Labs', 'Hostels', 'Sports', 'Incubation'],
    aiRatingScore: 76,
    overallRating: 4.0,
    isVerified: true,
  },
  {
    name: 'GL Bajaj Institute of Technology and Management',
    shortName: 'GL Bajaj',
    type: 'Private',
    tier: 'Tier 3',
    location: { city: 'Greater Noida', state: 'Uttar Pradesh', pincode: '201306' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 360, fees: 120000 },
      { name: 'B.Tech ME', duration: 4, seats: 120, fees: 110000 },
      { name: 'MBA', duration: 2, seats: 120, fees: 130000 },
    ],
    rankings: { nirf: 130 },
    averageFees: 120000,
    entranceExams: ['JEE Mains', 'UPSEE'],
    accreditation: 'NAAC B+',
    approvedBy: ['AICTE', 'UGC'],
    establishedYear: 2005,
    website: 'https://www.glbajajgroup.org',
    placementData: [{
      year: 2024, averagePackage: 4.5, highestPackage: 12,
      placementRate: 65, topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Tech Mahindra'],
    }],
    facilities: ['Library', 'Labs', 'Hostels', 'Sports Ground', 'Canteen'],
    aiRatingScore: 60,
    overallRating: 3.5,
    isVerified: true,
  },

  // ─── Gurgaon / Gurugram ───────────────────────────────────────
  {
    name: 'GD Goenka University',
    shortName: 'GD Goenka',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Gurgaon', state: 'Haryana', pincode: '122103' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 180, fees: 300000 },
      { name: 'BBA', duration: 3, seats: 180, fees: 200000 },
      { name: 'B.Design', duration: 4, seats: 60, fees: 280000 },
      { name: 'MBA', duration: 2, seats: 120, fees: 320000 },
    ],
    rankings: { nirf: 100 },
    averageFees: 300000,
    entranceExams: ['JEE Mains', 'GDG Entrance'],
    accreditation: 'NAAC A',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 2013,
    website: 'https://www.gdgoenka.ac.in',
    placementData: [{
      year: 2024, averagePackage: 6, highestPackage: 20,
      placementRate: 68, topRecruiters: ['Infosys', 'Wipro', 'EY', 'TCS', 'HCL'],
    }],
    facilities: ['Golf Course Campus', 'Sports', 'Labs', 'Hostels', 'Amphitheatre'],
    aiRatingScore: 67,
    overallRating: 3.7,
    isVerified: true,
  },

  // ─── Faridabad ────────────────────────────────────────────────
  {
    name: 'Manav Rachna University',
    shortName: 'MRU',
    type: 'Private',
    tier: 'Tier 2',
    location: { city: 'Faridabad', state: 'Haryana', pincode: '121004' },
    courses: [
      { name: 'B.Tech CSE', duration: 4, seats: 300, fees: 230000 },
      { name: 'BBA', duration: 3, seats: 240, fees: 150000 },
      { name: 'B.Sc Sports Science', duration: 3, seats: 60, fees: 120000 },
      { name: 'MBA', duration: 2, seats: 120, fees: 250000 },
    ],
    rankings: { nirf: 85 },
    averageFees: 230000,
    entranceExams: ['JEE Mains', 'MRU Entrance'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC', 'AICTE'],
    establishedYear: 2014,
    website: 'https://manavrachna.edu.in',
    placementData: [{
      year: 2024, averagePackage: 5.5, highestPackage: 18,
      placementRate: 68, topRecruiters: ['Infosys', 'TCS', 'Capgemini', 'Wipro'],
    }],
    facilities: ['Sports Complex', 'Labs', 'Hostels', 'Food Courts', 'Medical'],
    aiRatingScore: 65,
    overallRating: 3.7,
    isVerified: true,
  },

  // ─── Sonipat / Haryana (Near Delhi) ──────────────────────────
  {
    name: 'Ashoka University',
    shortName: 'Ashoka',
    type: 'Private',
    tier: 'Tier 1',
    location: { city: 'Sonipat', state: 'Haryana', pincode: '131029' },
    courses: [
      { name: 'B.A. (Hons) — Liberal Arts', duration: 4, seats: 600, fees: 900000 },
      { name: 'B.Sc. (Hons) — Economics', duration: 4, seats: 120, fees: 900000 },
      { name: 'M.A. Economics', duration: 2, seats: 60, fees: 600000 },
      { name: 'Ph.D.', duration: 5, seats: 50, fees: 100000 },
    ],
    rankings: { nirf: 9, qs: 1000 },
    averageFees: 900000,
    entranceExams: ['Ashoka Entrance', 'SAT', 'ACT'],
    accreditation: 'NAAC A+',
    approvedBy: ['UGC'],
    establishedYear: 2014,
    website: 'https://www.ashoka.edu.in',
    placementData: [{
      year: 2024, averagePackage: 12, highestPackage: 50,
      placementRate: 80, topRecruiters: ['McKinsey', 'BCG', 'Bain', 'Goldman Sachs', 'IAS/Civil Services'],
    }],
    facilities: ['World-class Campus', 'Library', 'Hostels', 'International Faculty', 'Research Centres'],
    aiRatingScore: 85,
    overallRating: 4.4,
    isVerified: true,
  },
  {
    name: 'O.P. Jindal Global University',
    shortName: 'JGU',
    type: 'Private',
    tier: 'Tier 1',
    location: { city: 'Sonipat', state: 'Haryana', pincode: '131001' },
    courses: [
      { name: 'BA LLB (Hons)', duration: 5, seats: 300, fees: 750000 },
      { name: 'B.Com (Hons)', duration: 3, seats: 240, fees: 550000 },
      { name: 'MBA', duration: 2, seats: 180, fees: 1000000 },
      { name: 'B.A. International Relations', duration: 3, seats: 180, fees: 600000 },
    ],
    rankings: { nirf: 1 }, // NIRF Law category
    averageFees: 750000,
    entranceExams: ['LSAT India', 'SAT', 'JGU Entrance'],
    accreditation: 'NAAC A++',
    approvedBy: ['UGC', 'BCI'],
    establishedYear: 2009,
    website: 'https://jgu.edu.in',
    placementData: [{
      year: 2024, averagePackage: 14, highestPackage: 60,
      placementRate: 85, topRecruiters: ['Cyril Amarchand Mangaldas', 'S&P', 'Luthra & Luthra', 'UN Orgs'],
    }],
    facilities: ['Moot Court', 'Law Library', 'Hostels', 'Sports', 'International Exchange Programs'],
    aiRatingScore: 87,
    overallRating: 4.4,
    isVerified: true,
  },
];

function toSlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

async function seedDB() {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/edu_discovery');
    console.log('✅ Connected to MongoDB');

    // Drop existing indexes to avoid stale index conflicts
    try { await mongoose.connection.db.collection('colleges').dropIndexes(); } catch {}

    await College.deleteMany({});
    console.log('🗑️  Cleared existing colleges');

    // insertMany bypasses pre-save hooks, so we pre-generate slugs
    const collegesWithSlugs = colleges.map(c => ({ ...c, slug: toSlug(c.name) }));
    const created = await College.insertMany(collegesWithSlugs, { ordered: true });
    console.log(`✅ Seeded ${created.length} colleges`);

    // Seed admin user
    await Student.deleteMany({ role: 'admin' });
    await Student.create({
      name: 'Admin User',
      email: 'admin@edudiscover.com',
      password: 'admin123',
      role: 'admin',
    });
    console.log('✅ Admin user created: admin@edudiscover.com / admin123');

    mongoose.disconnect();
    console.log('🎉 Seed complete!');
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
}

seedDB();
